### ISSUE TITLE
isAppStore is true on sideloaded IPA via AltStore

### ISSUE THREAD

**Issue by pfych** [Provenance-Emu/Provenance#2418]
When sideloading via the AltStore the Bundle identifier isn't changed, causing the `isAppStore` check to incorrectly set to true.

https://github.com/Provenance-Emu/Provenance/blob/521c3ee0bc232332f89dbb8d707b03b770386296/PVUI/Sources/PVSwiftUI/App%20Delegate/PVAppDelegate.swift#L75-L91

 
### Expected: 

`isAppStore` should be false

 
### Actual: 

`isAppStore` is true

 ### Reproduce:  

1. Download IPA from github
2. Sideload with AltStore
3. Launch Provenance

#

#### APP VERSION
3.1.0

#### APP SOURCE
- Provenance-Emu GitHub  *&nbsp;(Official)*

#### INSTALLED BY 
[Side-Loading](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/sideloading)

#### PLATFORM
iOS

#### iOS/tvOS VERSION
18.6

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
I think this is fixed in 3.2.0

**Comment by pfych** [comment]
Still experiencing this issue in 3.2.1 when sideloaded via altstore

**Comment by JoeMatt** [comment]
this should be fixed fr fr, this code was re-written for 3.3.x

You do need to change your bundle id from the stock one, but it no longer partially matches just the front part
